export const format = [
  { label: "Pdf", val: "pdf" },
  { label: "MS Doc", val: "doc" },
  { label: "Hand written", val: "hand" },
];
export const department = [
  {
    val: "Pharmacology",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/PCO.jpg?updatedAt=1746565335861",
  },
  {
    val: "Pharmacognsy",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/download%20(4).jpg?updatedAt=1746565335757",
  },
  {
    val: "Pharmaaceutical Microbiology",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/download%20(3).jpg?updatedAt=1746565335444",
  },
  {
    val: "Pharmaceutical Chemistry",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/PCH-1.jpg?updatedAt=1746565335580",
  },
  {
    val: "Pharmaceutics",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/PCT.jpg?updatedAt=1746565335502",
  },
  {
    val: "Clinical Pharmacy",
    url: "https://ik.imagekit.io/ikegwuonu/material%20cover/pcn2.jpg?updatedAt=1746565335803",
  },
  { val: "Physiology", url: "" },
  { val: "Biochemistry", url: "" },
  { val: "Anatomy", url: "" },
  { val: "Mathematics", url: "" },
];
export const faculties = ["Pharmacy"];

// Mock data for charts
export const userGrowthData = [
  { month: "Jan", users: 1200 },
  { month: "Feb", users: 1350 },
  { month: "Mar", users: 1500 },
  { month: "Apr", users: 1750 },
  { month: "May", users: 2100 },
  { month: "Jun", users: 2400 },
  { month: "Jul", users: 2800 },
  { month: "Aug", users: 3200 },
  { month: "Sep", users: 3600 },
  { month: "Oct", users: 4100 },
  { month: "Nov", users: 4500 },
  { month: "Dec", users: 5000 },
];

export const booksByCategoryData = [
  { name: "Fiction", value: 1250, color: "#8884d8" },
  { name: "Non-Fiction", value: 850, color: "#83a6ed" },
  { name: "Science Fiction", value: 620, color: "#8dd1e1" },
  { name: "Mystery", value: 580, color: "#82ca9d" },
  { name: "Biography", value: 450, color: "#a4de6c" },
  { name: "History", value: 380, color: "#d0ed57" },
  { name: "Self-Help", value: 320, color: "#ffc658" },
  { name: "Business", value: 280, color: "#ff8042" },
];

export const popularBooksData = [
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    views: 4500,
    borrows: 320,
  },
  { title: "Atomic Habits", author: "James Clear", views: 4200, borrows: 290 },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    views: 3800,
    borrows: 260,
  },
  {
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    views: 3600,
    borrows: 240,
  },
  {
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    views: 3400,
    borrows: 220,
  },
];

export const userActivityData = [
  { day: "Monday", logins: 450, searches: 1200, borrows: 85 },
  { day: "Tuesday", logins: 480, searches: 1350, borrows: 92 },
  { day: "Wednesday", logins: 520, searches: 1450, borrows: 105 },
  { day: "Thursday", logins: 490, searches: 1380, borrows: 98 },
  { day: "Friday", logins: 560, searches: 1580, borrows: 120 },
  { day: "Saturday", logins: 680, searches: 1820, borrows: 145 },
  { day: "Sunday", logins: 620, searches: 1650, borrows: 130 },
];

export const borrowsByAgeData = [
  { age: "Under 18", borrows: 1250 },
  { age: "18-24", borrows: 2450 },
  { age: "25-34", borrows: 3200 },
  { age: "35-44", borrows: 2800 },
  { age: "45-54", borrows: 1950 },
  { age: "55-64", borrows: 1200 },
  { age: "65+", borrows: 850 },
];

export const contentGrowthData = [
  { month: "Jan", books: 3200, textbooks: 1500 },
  { month: "Feb", books: 3250, textbooks: 1520 },
  { month: "Mar", books: 3320, textbooks: 1550 },
  { month: "Apr", books: 3450, textbooks: 1580 },
  { month: "May", books: 3600, textbooks: 1620 },
  { month: "Jun", books: 3750, textbooks: 1680 },
  { month: "Jul", books: 3900, textbooks: 1720 },
  { month: "Aug", books: 4050, textbooks: 1780 },
  { month: "Sep", books: 4200, textbooks: 1850 },
  { month: "Oct", books: 4350, textbooks: 1920 },
  { month: "Nov", books: 4500, textbooks: 1980 },
  { month: "Dec", books: 4730, textbooks: 2050 },
];

export const engagementTrendsData = [
  { month: "Jan", views: 12500, borrows: 850, completions: 720 },
  { month: "Feb", views: 13200, borrows: 920, completions: 780 },
  { month: "Mar", views: 14500, borrows: 1050, completions: 890 },
  { month: "Apr", views: 15800, borrows: 1150, completions: 980 },
  { month: "May", views: 17200, borrows: 1280, completions: 1090 },
  { month: "Jun", views: 18900, borrows: 1420, completions: 1210 },
  { month: "Jul", views: 20500, borrows: 1580, completions: 1340 },
  { month: "Aug", views: 22000, borrows: 1720, completions: 1460 },
  { month: "Sep", views: 23500, borrows: 1850, completions: 1570 },
  { month: "Oct", views: 24800, borrows: 1950, completions: 1660 },
  { month: "Nov", views: 26200, borrows: 2080, completions: 1770 },
  { month: "Dec", views: 28000, borrows: 2200, completions: 1870 },
];

export const featureUsageData = [
  { feature: "Search", usage: 42 },
  { feature: "Browse Categories", usage: 28 },
  { feature: "View Details", usage: 15 },
  { feature: "Borrow", usage: 8 },
  { feature: "Rate & Review", usage: 4 },
  { feature: "Save to List", usage: 3 },
];
export const materials = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Fiction",
    publicationYear: "2020",
    publisher: "Viking",
    language: "English",
    format: "Hardcover",
    pages: 304,
    rating: 4.2,
    reviews: 128,
    status: "available",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0525559474",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
  },
  {
    id: "2",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    genre: "Science Fiction",
    publicationYear: "2021",
    publisher: "Knopf",
    language: "English",
    format: "Hardcover",
    pages: 320,
    rating: 4.1,
    reviews: 95,
    status: "borrowed",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0593318171",
    description:
      "From the Nobel Prize-winning author, a novel about an Artificial Friend who observes the world around her, watching and learning about human behavior.",
  },
  {
    id: "3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Science Fiction",
    publicationYear: "2021",
    publisher: "Ballantine Books",
    language: "English",
    format: "Ebook",
    pages: 496,
    rating: 4.7,
    reviews: 210,
    status: "available",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0593135204",
    description:
      "A lone astronaut must save the earth from disaster in this incredible new science-based thriller from the #1 New York Times bestselling author of The Martian.",
  },
  {
    id: "4",
    title: "The Four Winds",
    author: "Kristin Hannah",
    genre: "Historical Fiction",
    publicationYear: "2021",
    publisher: "St. Martin's Press",
    language: "English",
    format: "Paperback",
    pages: 464,
    rating: 4.5,
    reviews: 175,
    status: "available",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-1250178602",
    description:
      "From the number-one bestselling author of The Nightingale and The Great Alone comes a powerful American epic about love and heroism and hope, set during the Great Depression.",
  },
  {
    id: "5",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    genre: "Fantasy",
    publicationYear: "2020",
    publisher: "Tor Books",
    language: "English",
    format: "Audiobook",
    pages: 448,
    rating: 4.4,
    reviews: 156,
    status: "reserved",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0765387561",
    description:
      "A Life No One Will Remember. A Story You Will Never Forget. In a desperate bargain, Addie surrenders her life to live forever—and is cursed to be forgotten by everyone she meets.",
  },
  {
    id: "6",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    publicationYear: "2018",
    publisher: "Avery",
    language: "English",
    format: "Hardcover",
    pages: 320,
    rating: 4.8,
    reviews: 320,
    status: "borrowed",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0735211292",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear reveals practical strategies that will teach you how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
  },
  {
    id: "7",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    genre: "Historical Fiction",
    publicationYear: "2012",
    publisher: "Ecco",
    language: "English",
    format: "Paperback",
    pages: 416,
    rating: 4.6,
    reviews: 189,
    status: "available",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0062060624",
    description:
      "A tale of gods, kings, immortal fame, and the human heart, The Song of Achilles is a dazzling literary feat that brilliantly reimagines Homer's enduring masterwork, The Iliad.",
  },
  {
    id: "8",
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    publicationYear: "2018",
    publisher: "Random House",
    language: "English",
    format: "Ebook",
    pages: 352,
    rating: 4.7,
    reviews: 245,
    status: "available",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0399590504",
    description:
      "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
  },
  {
    id: "9",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Fiction",
    publicationYear: "2018",
    publisher: "G.P. Putnam's Sons",
    language: "English",
    format: "Paperback",
    pages: 384,
    rating: 4.8,
    reviews: 278,
    status: "borrowed",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-0735219090",
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.",
  },
  {
    id: "10",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Thriller",
    publicationYear: "2019",
    publisher: "Celadon Books",
    language: "English",
    format: "Audiobook",
    pages: 336,
    rating: 4.5,
    reviews: 198,
    status: "reserved",
    coverUrl: "/placeholder.svg?height=120&width=90",
    isbn: "978-1250301697",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
  },
];
export const textbooks = [
  {
    id: "1",
    title: "Introduction to Computer Science",
    author: "John Smith, Jane Doe",
    edition: "3rd Edition",
    isbn: "978-1234567890",
    category: "Computer Science",
    status: "published",
    addedBy: "John Doe",
    createdAt: new Date("2023-08-15"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Academic Press",
    year: "2023",
    pages: 450,
    language: "English",
  },
  {
    id: "2",
    title: "Principles of Economics",
    author: "Robert Johnson",
    edition: "5th Edition",
    isbn: "978-0987654321",
    category: "Economics",
    status: "published",
    addedBy: "Jane Smith",
    createdAt: new Date("2023-07-22"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "University Press",
    year: "2022",
    pages: 620,
    language: "English",
  },
  {
    id: "3",
    title: "Organic Chemistry",
    author: "Michael Brown, Sarah Davis",
    edition: "2nd Edition",
    isbn: "978-5678901234",
    category: "Chemistry",
    status: "published",
    addedBy: "Robert Johnson",
    createdAt: new Date("2023-09-05"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Science Publications",
    year: "2023",
    pages: 580,
    language: "English",
  },
  {
    id: "4",
    title: "Calculus: Early Transcendentals",
    author: "Emily Williams",
    edition: "8th Edition",
    isbn: "978-6789012345",
    category: "Mathematics",
    status: "published",
    addedBy: "John Doe",
    createdAt: new Date("2023-06-18"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Math Press",
    year: "2021",
    pages: 720,
    language: "English",
  },
  {
    id: "5",
    title: "Introduction to Psychology",
    author: "David Miller",
    edition: "4th Edition",
    isbn: "978-7890123456",
    category: "Psychology",
    status: "draft",
    addedBy: "Sarah Davis",
    createdAt: new Date("2023-10-10"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Behavioral Sciences",
    year: "2023",
    pages: 510,
    language: "English",
  },
  {
    id: "6",
    title: "World History: A Comprehensive Guide",
    author: "Lisa Wilson, Thomas Anderson",
    edition: "6th Edition",
    isbn: "978-8901234567",
    category: "History",
    status: "published",
    addedBy: "Michael Brown",
    createdAt: new Date("2023-05-25"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Historical Press",
    year: "2022",
    pages: 850,
    language: "English",
  },
  {
    id: "7",
    title: "Fundamentals of Physics",
    author: "Richard Taylor",
    edition: "10th Edition",
    isbn: "978-9012345678",
    category: "Physics",
    status: "published",
    addedBy: "Emily Williams",
    createdAt: new Date("2023-07-08"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Science Academy",
    year: "2023",
    pages: 680,
    language: "English",
  },
  {
    id: "8",
    title: "Introduction to Literature",
    author: "Jennifer Clark",
    edition: "1st Edition",
    isbn: "978-0123456789",
    category: "Literature",
    status: "review",
    addedBy: "David Miller",
    createdAt: new Date("2023-09-30"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Arts & Humanities",
    year: "2023",
    pages: 420,
    language: "English",
  },
  {
    id: "9",
    title: "Database Systems: Concepts and Design",
    author: "Mark Johnson, Laura Smith",
    edition: "7th Edition",
    isbn: "978-1357924680",
    category: "Computer Science",
    status: "published",
    addedBy: "John Doe",
    createdAt: new Date("2023-08-05"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Tech Publications",
    year: "2022",
    pages: 720,
    language: "English",
  },
  {
    id: "10",
    title: "Human Anatomy and Physiology",
    author: "Susan White",
    edition: "9th Edition",
    isbn: "978-2468013579",
    category: "Biology",
    status: "published",
    addedBy: "Lisa Wilson",
    createdAt: new Date("2023-06-12"),
    coverUrl: "/placeholder.svg?height=120&width=90",
    publisher: "Medical Press",
    year: "2021",
    pages: 890,
    language: "English",
  },
];
// Sample data for admins

// Define admin role types and permissions
export const roles = [
  {
    id: "super-admin",
    name: "Super Admin",
    description: "Full access to all system features and settings",
    permissions: [
      "Manage admins",
      "Manage users",
      "Manage content",
      "View analytics",
      "System settings",
    ],
  },
  {
    id: "content-manager",
    name: "Content Manager",
    description: "Manage books, categories, and content",
    permissions: [
      "Add/edit books",
      "Manage categories",
      "Moderate reviews",
      "Manage featured content",
    ],
  },
  {
    id: "user-manager",
    name: "User Manager",
    description: "Manage user accounts and subscriptions",
    permissions: [
      "View user accounts",
      "Edit user details",
      "Manage subscriptions",
      "Handle user support",
    ],
  },
  {
    id: "analytics-viewer",
    name: "Analytics Viewer",
    description: "View reports and analytics only",
    permissions: [
      "View reading statistics",
      "View user growth",
      "View content performance",
      "Export reports",
    ],
  },
];
