export const pharmacyCourses = [
  {
    courseCode: "ANT212",
    creditScore: 1,
    courseTitle: "Anatomy I (Basic Anatomy)",
    semester: "First",
    level: "200",
    department: "Anatomy",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "BCH219",
    creditScore: 4,
    courseTitle: "Biochemistry I",
    semester: "First",
    level: "200",
    department: "Biochemistry",
    faculty: "Life Science",
  },
  {
    courseCode: "PHM215",
    creditScore: 2,
    courseTitle: "Ancillary Mathematics I",
    semester: "First",
    level: "200",
    department: "Mathematics",
    faculty: "Life Science",
  },
  {
    courseCode: "PHS212",
    creditScore: 2,
    courseTitle: "Introductory and Blood Physiology",
    semester: "First",
    level: "200",
    department: "Physiology",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "PHS213",
    creditScore: 2,
    courseTitle: "Cardiovascular and Respiratory Physiology",
    semester: "First",
    level: "200",
    department: "Physiology",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "PCG212",
    creditScore: 2,
    courseTitle: "Introduction to Pharmacognosy",
    semester: "First",
    level: "200",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG211",
    creditScore: 1,
    courseTitle: "Pharmacognosy Practical",
    semester: "First",
    level: "200",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT213",
    creditScore: 2,
    courseTitle: "Introduction to Pharmacy and Pharmaceutics",
    semester: "First",
    level: "200",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT201",
    creditScore: 0,
    courseTitle: "Pharmaceutics Practical (Dispensing)",
    semester: "First",
    level: "200",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH212",
    creditScore: 2,
    courseTitle: "Pharmaceutical Chemistry I",
    semester: "First",
    level: "200",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH211",
    creditScore: 0,
    courseTitle: "Pharmaceutical Chemistry Practical",
    semester: "First",
    level: "200",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB212",
    creditScore: 2,
    courseTitle: "Principles of Pharmaceutical Microbiology",
    semester: "First",
    level: "200",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "ANT222",
    creditScore: 3,
    courseTitle:
      "Anatomy II (General Embryology, Teratology & Genetic Anatomy)",
    semester: "Second",
    level: "200",
    department: "Anatomy",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "BCH229",
    creditScore: 2,
    courseTitle: "Biochemistry II",
    semester: "Second",
    level: "200",
    department: "Biochemistry",
    faculty: "Life Science",
  },
  {
    courseCode: "PHM225",
    creditScore: 2,
    courseTitle: "Ancillary Mathematics II",
    semester: "Second",
    level: "200",
    department: "Mathematics",
    faculty: "Life Science",
  },
  {
    courseCode: "PHS224",
    creditScore: 2,
    courseTitle: "Renal, Gastrointestinal and Endocrine Physiology",
    semester: "Second",
    level: "200",
    department: "Physiology",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "PHS225",
    creditScore: 2,
    courseTitle: "Neurophysiology and Special Senses",
    semester: "Second",
    level: "200",
    department: "Physiology",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "PCH223",
    creditScore: 2,
    courseTitle: "Pharmaceutical Chemistry II",
    semester: "Second",
    level: "200",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB221",
    creditScore: 1,
    courseTitle: "Pharmaceutical Microbiology I Practical",
    semester: "Second",
    level: "200",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT221",
    creditScore: 1,
    courseTitle: "Pharmaceutics Practical (Dispensing)",
    semester: "Second",
    level: "200",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH221",
    creditScore: 1,
    courseTitle: "Pharmaceutical Chemistry Practical",
    semester: "Second",
    level: "200",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PHS202",
    creditScore: 1,
    courseTitle: "Physiology Practical",
    semester: "Second",
    level: "200",
    department: "Physiology",
    faculty: "Basic Medical Science",
  },
  {
    courseCode: "PCO314",
    creditScore: 3,
    courseTitle: "General Principles of Pharmacology",
    semester: "First",
    level: "300",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO315",
    creditScore: 3,
    courseTitle: "Autonomic/Neuro-pharmacology",
    semester: "First",
    level: "300",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO301",
    creditScore: 0,
    courseTitle: "Pharmacology I Practical",
    semester: "First",
    level: "300",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "CPH301",
    creditScore: 3,
    courseTitle: "Basic Computing and Information Technology",
    semester: "First",
    level: "300",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB312",
    creditScore: 3,
    courseTitle: "Disinfection and Sterilisation",
    semester: "First",
    level: "300",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH311",
    creditScore: 1,
    courseTitle: "Pharmaceutical Chemistry Practical II",
    semester: "First",
    level: "300",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH312",
    creditScore: 3,
    courseTitle: "Pharmaceutical Organic Chemistry I",
    semester: "First",
    level: "300",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT313",
    creditScore: 3,
    courseTitle: "Pharmaceutical Technology I",
    semester: "First",
    level: "300",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT301",
    creditScore: 0,
    courseTitle: "Pharmaceutics II Practical (Dispensing II)",
    semester: "First",
    level: "300",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "CED300",
    creditScore: 2,
    courseTitle: "Entrepreneurship Development",
    semester: "First",
    level: "300",
    department: "Entrepreneurship",
    faculty: "Education",
  },
  {
    courseCode: "PCO324",
    creditScore: 3,
    courseTitle: "Systemic Pharmacology",
    semester: "Second",
    level: "300",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB321",
    creditScore: 1,
    courseTitle: "Pharmaceutical Microbiology II Practical",
    semester: "Second",
    level: "300",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH322",
    creditScore: 2,
    courseTitle: "Pharmaceutical Analysis I",
    semester: "Second",
    level: "300",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH323",
    creditScore: 2,
    courseTitle: "Pharmaceutical Organic Chemistry II",
    semester: "Second",
    level: "300",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG322",
    creditScore: 2,
    courseTitle: "Medicinal Plants and Alternative Medicine II",
    semester: "Second",
    level: "300",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG321",
    creditScore: 1,
    courseTitle: "Pharmacognosy II Practical",
    semester: "Second",
    level: "300",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT323",
    creditScore: 3,
    courseTitle: "Physical Pharmaceutics",
    semester: "Second",
    level: "300",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG312",
    creditScore: 0,
    courseTitle: "Medicinal Plants and Alternative Medicine I",
    semester: "Second",
    level: "300",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR412",
    creditScore: 2,
    courseTitle: "Pharmacy Management",
    semester: "First",
    level: "400",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN412",
    creditScore: 3,
    courseTitle: "Clinical Pharmacokinetics",
    semester: "First",
    level: "400",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH412",
    creditScore: 3,
    courseTitle: "Medicinal Chemistry I",
    semester: "First",
    level: "400",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PIT401",
    creditScore: 4,
    courseTitle: "Industrial Training (SIWES)",
    semester: "First",
    level: "400",
    department: "IT",
    faculty: "Education",
  },
  {
    courseCode: "PCT413",
    creditScore: 3,
    courseTitle: "Pharmaceutical Technology II",
    semester: "First",
    level: "400",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR422",
    creditScore: 2,
    courseTitle: "Pharmacy Entrepreneurship",
    semester: "Second",
    level: "400",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR423",
    creditScore: 2,
    courseTitle: "Pharmacy Law and Ethics (Jurisprudence)",
    semester: "Second",
    level: "400",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN422",
    creditScore: 3,
    courseTitle: "Pathophysiology (Incorporating Pathology)",
    semester: "Second",
    level: "400",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO421",
    creditScore: 1,
    courseTitle: "Pharmacology II Practical",
    semester: "Second",
    level: "400",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO422",
    creditScore: 3,
    courseTitle: "Central Nervous System Pharmacology",
    semester: "Second",
    level: "400",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO423",
    creditScore: 2,
    courseTitle: "Chemotherapy",
    semester: "Second",
    level: "400",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB421",
    creditScore: 2,
    courseTitle: "Pharmaceutical Microbiology III",
    semester: "Second",
    level: "400",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH421",
    creditScore: 1,
    courseTitle: "Pharmaceutical Chemistry Practical III",
    semester: "Second",
    level: "400",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG421",
    creditScore: 1,
    courseTitle: "Pharmacognosy III Practical",
    semester: "Second",
    level: "400",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB423",
    creditScore: 1,
    courseTitle: "Sterile Products Formulation and Immunology",
    semester: "Second",
    level: "400",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG422",
    creditScore: 3,
    courseTitle: "Phytochemistry I",
    semester: "Second",
    level: "400",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT421",
    creditScore: 0,
    courseTitle: "Powder and Tablet Technology",
    semester: "Second",
    level: "400",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO512",
    creditScore: 3,
    courseTitle: "Endocrine/Autocoid Pharmacology",
    semester: "First",
    level: "500",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN512",
    creditScore: 2,
    courseTitle: "Pharmacotherapeutics I",
    semester: "First",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN513",
    creditScore: 2,
    courseTitle: "Patient Assessment and Drug Administration",
    semester: "First",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR512",
    creditScore: 2,
    courseTitle: "Pharmacoeconomics & Pharmacy Practice",
    semester: "First",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB512",
    creditScore: 3,
    courseTitle: "Microbial Chemotherapy & Bacterial Genetics",
    semester: "First",
    level: "500",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH511",
    creditScore: 1,
    courseTitle: "Pharmaceutical Analysis Practical",
    semester: "First",
    level: "500",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH512",
    creditScore: 3,
    courseTitle: "Medicinal Chemistry II",
    semester: "First",
    level: "500",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCG512",
    creditScore: 2,
    courseTitle: "Phytochemistry II",
    semester: "First",
    level: "500",
    department: "Pharmacognosy",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT512",
    creditScore: 2,
    courseTitle: "Formulation and Production of Phytomedicines",
    semester: "First",
    level: "500",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCH523",
    creditScore: 2,
    courseTitle: "Pharmaceutical Analysis II",
    semester: "Second",
    level: "500",
    department: "Pharmaceutical Chemistry",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PTX522",
    creditScore: 2,
    courseTitle: "Clinical & Environmental Toxicology",
    semester: "Second",
    level: "500",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN521",
    creditScore: 3,
    courseTitle: "Clinical Pharmacy Clerkship I",
    semester: "Second",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN522",
    creditScore: 2,
    courseTitle: "Pharmacotherapeutics II",
    semester: "Second",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN524",
    creditScore: 2,
    courseTitle: "Advanced Communication Skills",
    semester: "Second",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR521",
    creditScore: 1,
    courseTitle: "Professional Dispensing",
    semester: "Second",
    level: "500",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB522",
    creditScore: 2,
    courseTitle: "Infectious Diseases & Pathogenesis",
    semester: "Second",
    level: "500",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PMB523",
    creditScore: 2,
    courseTitle: "Preservation and Fermentation Biotechnology",
    semester: "Second",
    level: "500",
    department: "Pharmaceutical Microbiology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT522",
    creditScore: 2,
    courseTitle: "Biopharmaceutics",
    semester: "Second",
    level: "500",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCT523",
    creditScore: 2,
    courseTitle: "Dosage Form Evaluation and Drug Stability",
    semester: "Second",
    level: "500",
    department: "Pharmaceutics and Pharmaceutical Technology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN610",
    creditScore: 2,
    courseTitle: "Biostatistics & Research Methodology",
    semester: "First",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN612",
    creditScore: 2,
    courseTitle: "Pharmaceutical Care",
    semester: "First",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPR612",
    creditScore: 2,
    courseTitle: "Supply Chain Management",
    semester: "First",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO612",
    creditScore: 2,
    courseTitle: "Health Psychology & Substance Abuse",
    semester: "First",
    level: "600",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCO613",
    creditScore: 2,
    courseTitle: "Haemopoeitic/Biochemical Pharmacology",
    semester: "First",
    level: "600",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PHV612",
    creditScore: 2,
    courseTitle: "Veterinary Pharmacy",
    semester: "First",
    level: "600",
    department: "Pharmacology & Toxicology",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PPJ601",
    creditScore: 4,
    courseTitle: "Project",
    semester: "Second",
    level: "600",
    department: "Project",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN620",
    creditScore: 2,
    courseTitle: "Drug Information Service",
    semester: "Second",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN621",
    creditScore: 7,
    courseTitle: "Clinical Pharmacy Clerkship III",
    semester: "Second",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN622",
    creditScore: 2,
    courseTitle: "Public Health Pharmacy & Pharmacoepidemiology",
    semester: "Second",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN624",
    creditScore: 2,
    courseTitle: "Pharmacotherapeutics III",
    semester: "Second",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
  {
    courseCode: "PCN625",
    creditScore: 1,
    courseTitle: "Seminar",
    semester: "Second",
    level: "600",
    department: "Clinical Pharmacy and Pharmacy Practice",
    faculty: "Pharmacy",
  },
];
